function outputtable = importCsvFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MEASUREMENTS1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MEASUREMENTS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  measurements1 = importfile("C:\Users\Enrico\Google Drive\phD\EMG_elNet_Dynamic\Data\2_KAMINISHI\mri\ROIs\proxP\measurements.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jul-2020 11:15:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Label", "Area", "X", "Y", "XM", "YM"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Label", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Label", "EmptyFieldRule", "auto");

% Import the data
outputtable = readtable(filename, opts);

end